CREATE TABLESPACE dari
    DATAFILE 'dari01.dat' SIZE 50M REUSE
    AUTOEXTEND ON NEXT 50M MAXSIZE 10000M;

CREATE USER dari
    IDENTIFIED by dari
    DEFAULT TABLESPACE dari
    QUOTA UNLIMITED ON dari;

GRANT CREATE SESSION TO dari;
GRANT CREATE TRIGGER TO dari;
GRANT CREATE TABLE to dari;
GRANT CREATE SEQUENCE to dari;
